
import { Epoch, Upgrade, Resource, CosmicLaw, RandomEvent, Achievement, PrestigeUpgrade } from './types';

export const ACHIEVEMENT_BONUS_MULTIPLIER = 10;
export const ACHIEVEMENT_BONUS_DURATION_MS = 10000;

export const EPOCHS: Epoch[] = [
  {
    name: 'The Void',
    time: 'Before Time',
    description: 'An unnerving emptiness. Perhaps a little tap is in order?',
    unlockCost: 0,
    unlockResource: Resource.ENERGY,
    particleConfig: { count: 5, colors: ['#4a5568'], minSpeed: 0.1, maxSpeed: 0.2, minSize: 1, maxSize: 2 },
  },
  {
    name: 'Planck Epoch & The Big Bang',
    time: '0 – 10⁻⁴³ s',
    description: 'A singularity of unimaginable density. All forces are unified. You created... everything!',
    unlockCost: 100,
    unlockResource: Resource.ENERGY,
    particleConfig: { count: 100, colors: ['#fefcbf', '#fbb040', '#f7941d'], minSpeed: 1, maxSpeed: 5, minSize: 1, maxSize: 3 },
  },
  {
    name: 'Quark-Gluon Plasma',
    time: '10⁻¹² – 10⁻⁶ s',
    description: 'The universe is a hot, dense soup of quarks and gluons. Too hot for protons to form yet!',
    unlockCost: 50,
    unlockResource: Resource.QUARK,
    particleConfig: { count: 200, colors: ['#be1e2d', '#f15a24', '#f7931e'], minSpeed: 0.5, maxSpeed: 1.5, minSize: 2, maxSize: 4 },
  },
  {
    name: 'Hadron & Lepton Epochs',
    time: '10⁻⁶ s – 3 min',
    description: 'Quarks are now cool enough to form Protons. The universe is taking shape.',
    unlockCost: 100,
    unlockResource: Resource.PROTON,
    particleConfig: { count: 150, colors: ['#4fa3e4', '#ffffff', '#a2d4ec'], minSpeed: 0.3, maxSpeed: 0.8, minSize: 1, maxSize: 3 },
  },
  {
      name: 'Nucleosynthesis',
      time: '3 – 20 min',
      description: 'Protons and neutrons fuse to form the first atomic nuclei. Mostly Hydrogen and Helium.',
      unlockCost: 500,
      unlockResource: Resource.ATOM,
      particleConfig: { count: 300, colors: ['#93278f', '#f26522', '#662d91'], minSpeed: 0.2, maxSpeed: 0.6, minSize: 2, maxSize: 5},
  },
  {
      name: 'The First Stars',
      time: '150 Myr onward',
      description: 'Gravitational collapse ignites the first stars, ending the cosmic Dark Ages. Let there be light!',
      unlockCost: 100,
      unlockResource: Resource.STAR,
      particleConfig: { count: 400, colors: ['#fff200', '#f7941d', '#f15a24', '#ebebeb'], minSpeed: 0.1, maxSpeed: 0.4, minSize: 1, maxSize: 6},
  },
  {
    name: 'Galaxy Formation',
    time: '200 Myr - 1 Gyr',
    description: 'Gravity pulls stars and gas clouds into immense, swirling structures. The first galaxies begin to light up the cosmos.',
    unlockCost: 1000,
    unlockResource: Resource.STAR,
    particleConfig: { count: 50, colors: ['#ffffff', '#a2d4ec', '#93278f', '#fefcbf'], minSpeed: 0.1, maxSpeed: 0.3, minSize: 1, maxSize: 5 },
  }
];

export const UPGRADES: Record<string, Upgrade> = {
  'energy_click_1': {
    id: 'energy_click_1',
    name: 'Quantum Fluctuation',
    description: '+1 Energy per click.',
    flavorText: 'Tickle spacetime and see what giggles out.',
    costResource: Resource.ENERGY,
    baseCost: 10,
    costMultiplier: 1.15,
    effects: [{ type: 'click', resource: Resource.ENERGY, value: 1 }],
    requiredEpoch: 0,
    position: { x: 50, y: 90 },
  },
  'energy_click_2': {
    id: 'energy_click_2',
    name: 'Higgs Field Manipulation',
    description: '+5 Energy per click.',
    flavorText: 'Giving things mass is so last epoch.',
    costResource: Resource.ENERGY,
    baseCost: 500,
    costMultiplier: 1.25,
    effects: [{ type: 'click', resource: Resource.ENERGY, value: 5 }],
    requiredEpoch: 1,
    position: { x: 70, y: 80 },
    parents: ['energy_click_1'],
  },
  'energy_click_3': {
    id: 'energy_click_3',
    name: 'Inflationary Burst',
    description: '+25 Energy per click.',
    flavorText: 'The universe is expanding, and so is your potential.',
    costResource: Resource.ENERGY,
    baseCost: 5000,
    costMultiplier: 1.3,
    effects: [{ type: 'click', resource: Resource.ENERGY, value: 25 }],
    requiredEpoch: 3,
    position: { x: 80, y: 65 },
    parents: ['energy_click_2'],
  },
  'energy_click_4': {
    id: 'energy_click_4',
    name: 'Electroweak Symmetry Breaking',
    description: '+100 Energy per click.',
    flavorText: 'Splitting forces is a great way to release some energy.',
    costResource: Resource.ENERGY,
    baseCost: 50000,
    costMultiplier: 1.35,
    effects: [{ type: 'click', resource: Resource.ENERGY, value: 100 }],
    requiredEpoch: 4,
    position: { x: 85, y: 45 },
    parents: ['energy_click_3'],
  },
  'energy_click_5': {
    id: 'energy_click_5',
    name: 'Stellar Fusion',
    description: '+500 Energy per click.',
    flavorText: 'Harness the power of a baby star in every tap.',
    costResource: Resource.ENERGY,
    baseCost: 1000000,
    costMultiplier: 1.4,
    effects: [{ type: 'click', resource: Resource.ENERGY, value: 500 }],
    requiredEpoch: 5,
    position: { x: 90, y: 25 },
    parents: ['energy_click_4'],
  },
  
  // Quark Branch (Left Side)
  'quark_unlock': {
    id: 'quark_unlock',
    name: 'Primordial Soup',
    description: 'Clicks now also generate Quarks.',
    flavorText: 'It\'s like alphabet soup, but for reality.',
    costResource: Resource.ENERGY,
    baseCost: 250,
    costMultiplier: 1,
    maxLevel: 1,
    effects: [{ type: 'click', resource: Resource.QUARK, value: 1 }],
    requiredEpoch: 1,
    position: { x: 30, y: 80 },
    parents: ['energy_click_1'],
  },
  'energy_to_quark_conversion': {
    id: 'energy_to_quark_conversion',
    name: 'Pair Production',
    description: '+1 Quark per click.',
    flavorText: 'Borrowing from the vacuum to create matter. What could go wrong?',
    costResource: Resource.ENERGY,
    baseCost: 300,
    costMultiplier: 1.2,
    effects: [{ type: 'click', resource: Resource.QUARK, value: 1 }],
    requiredEpoch: 2,
    position: { x: 15, y: 75 },
    parents: ['quark_unlock'],
  },
  'quark_idle_1': {
    id: 'quark_idle_1',
    name: 'Gluon Bonds',
    description: '+0.1 Quarks per second.',
    flavorText: 'The universe\'s strongest superglue.',
    costResource: Resource.QUARK,
    baseCost: 10,
    costMultiplier: 1.2,
    effects: [{ type: 'idle', resource: Resource.QUARK, value: 0.1 }],
    requiredEpoch: 1,
    position: { x: 30, y: 65 },
    parents: ['quark_unlock'],
  },
  'quark_idle_2': {
    id: 'quark_idle_2',
    name: 'Quark Confinement',
    description: '+1 Quark per second.',
    flavorText: 'They really prefer to stick together in groups.',
    costResource: Resource.QUARK,
    baseCost: 100,
    costMultiplier: 1.25,
    effects: [{ type: 'idle', resource: Resource.QUARK, value: 1 }],
    requiredEpoch: 1,
    position: { x: 20, y: 55 },
    parents: ['quark_idle_1'],
  },

  // Proton Branch (Middle-Left)
  'proton_unlock': {
    id: 'proton_unlock',
    name: 'Baryogenesis',
    description: 'Convert 3 Quarks into 1 Proton per click.',
    flavorText: 'The universe learns a new trick: bundling quarks into something more substantial. A matter of importance!',
    costResource: Resource.QUARK,
    baseCost: 1000,
    costMultiplier: 1,
    maxLevel: 1,
    effects: [], 
    requiredEpoch: 3,
    position: { x: 40, y: 60 },
    parents: ['quark_idle_1'],
  },
   'proton_formation': {
    id: 'proton_formation',
    name: 'Proton Formation',
    description: 'Convert 100 Quarks into 1 Proton per click.',
    flavorText: 'An alternative, less efficient path to matter emerges from the quantum foam.',
    costResource: Resource.QUARK,
    baseCost: 500,
    costMultiplier: 1,
    maxLevel: 1,
    effects: [], 
    requiredEpoch: 3,
    position: { x: 50, y: 65 },
    parents: ['quark_idle_1'],
  },
  'proton_idle_1': {
      id: 'proton_idle_1',
      name: 'Strong Nuclear Force',
      description: '+0.1 Protons per second.',
      flavorText: 'It\'s what holds you together. Literally.',
      costResource: Resource.QUARK,
      baseCost: 250,
      costMultiplier: 1.3,
      effects: [{type: 'idle', resource: Resource.PROTON, value: 0.1}],
      requiredEpoch: 2,
      position: { x: 35, y: 50 },
      parents: ['proton_unlock'],
  },
  'proton_idle_2': {
      id: 'proton_idle_2',
      name: 'Baryon Asymmetry',
      description: '+1 Proton per second.',
      flavorText: 'For every billion antiparticles, there was a billion and one particle. Lucky you.',
      costResource: Resource.PROTON,
      baseCost: 200,
      costMultiplier: 1.35,
      effects: [{type: 'idle', resource: Resource.PROTON, value: 1}],
      requiredEpoch: 3,
      position: { x: 25, y: 40 },
      parents: ['proton_idle_1'],
  },

  // Atom Branch (Middle)
  'atom_unlock': {
    id: 'atom_unlock',
    name: 'Recombination',
    description: 'Unlocks the ability to convert 1 Proton into 1 Hydrogen Atom per click.',
    flavorText: 'The universe just became transparent. And a little less lonely for protons.',
    costResource: Resource.PROTON,
    baseCost: 2000,
    costMultiplier: 1,
    maxLevel: 1,
    effects: [], 
    requiredEpoch: 3,
    position: { x: 50, y: 45 },
    parents: ['proton_unlock'],
  },
  'atom_click_1': {
    id: 'atom_click_1',
    name: 'Electron Shell Configuration',
    description: '+1 Hydrogen Atom per click (consumes 1 Proton).',
    flavorText: 'Turns out electrons are social and like to orbit in specific circles.',
    costResource: Resource.ATOM,
    baseCost: 150,
    costMultiplier: 1.4,
    effects: [{ type: 'click', resource: Resource.ATOM, value: 1 }],
    requiredEpoch: 4,
    position: { x: 60, y: 40 },
    parents: ['atom_unlock'],
  },
  'atom_idle_1': {
      id: 'atom_idle_1',
      name: 'Electron Capture',
      description: '+0.1 Hydrogen Atoms per second.',
      flavorText: 'It\'s a universal matchmaking service for lonely protons and electrons.',
      costResource: Resource.ATOM,
      baseCost: 50,
      costMultiplier: 1.3,
      effects: [{type: 'idle', resource: Resource.ATOM, value: 0.1}],
      requiredEpoch: 4,
      position: { x: 45, y: 35 },
      parents: ['atom_unlock'],
  },

  // Star Branch (Top)
  'star_unlock': {
      id: 'star_unlock',
      name: 'Stellar Nursery',
      description: 'Convert 1000 Hydrogen Atoms into 1 Star per click.',
      flavorText: 'A star is born! Please, no paparazzi.',
      costResource: Resource.ATOM,
      baseCost: 5000,
      costMultiplier: 1,
      maxLevel: 1,
      effects: [],
      requiredEpoch: 4,
      position: { x: 50, y: 25 },
      parents: ['atom_idle_1'],
  },
  'star_idle_1': {
    id: 'star_idle_1',
    name: 'Protostar Formation',
    description: '+0.1 Stars per second.',
    flavorText: 'Gravity\'s patient work, collapsing cosmic clouds into celestial furnaces.',
    costResource: Resource.STAR,
    baseCost: 10,
    costMultiplier: 1.5,
    effects: [{type: 'idle', resource: Resource.STAR, value: 0.1}],
    requiredEpoch: 5,
    position: { x: 35, y: 20 },
    parents: ['star_unlock'],
  },
  'star_idle_2': {
    id: 'star_idle_2',
    name: 'Galactic Nucleus',
    description: '+1 Star per second.',
    flavorText: 'At the heart of the galaxy, a supermassive black hole\'s accretion disk is a stellar forge.',
    costResource: Resource.STAR,
    baseCost: 100,
    costMultiplier: 1.55,
    effects: [{type: 'idle', resource: Resource.STAR, value: 1}],
    requiredEpoch: 5,
    position: { x: 25, y: 15 },
    parents: ['star_idle_1'],
  },
  'star_idle_3': {
    id: 'star_idle_3',
    name: 'Supernova Chain Reaction',
    description: '+10 Stars per second.',
    flavorText: 'The explosive death of one star seeds the birth of a hundred more.',
    costResource: Resource.STAR,
    baseCost: 1000,
    costMultiplier: 1.6,
    effects: [{type: 'idle', resource: Resource.STAR, value: 10}],
    requiredEpoch: 5,
    position: { x: 40, y: 10 },
    parents: ['star_idle_2'],
  },
   'star_idle_4': {
    id: 'star_idle_4',
    name: 'Quasar Ignition',
    description: '+100 Stars per second.',
    flavorText: 'The accretion disk of a supermassive black hole, outshining entire galaxies.',
    costResource: Resource.STAR,
    baseCost: 10000,
    costMultiplier: 1.65,
    effects: [{type: 'idle', resource: Resource.STAR, value: 100}],
    requiredEpoch: 5,
    position: { x: 60, y: 15 },
    parents: ['star_unlock'],
  },
  'star_idle_5': {
    id: 'star_idle_5',
    name: 'Stellar Forge',
    description: '+10,000 Stars per second.',
    flavorText: 'Forge entire constellations in an instant by commanding the gravity of a supercluster.',
    costResource: Resource.STAR,
    baseCost: 1000000,
    costMultiplier: 1.75,
    effects: [{type: 'idle', resource: Resource.STAR, value: 10000}],
    requiredEpoch: 6,
    position: { x: 70, y: 10 },
    parents: ['star_idle_4'],
  },
  'star_idle_6': {
    id: 'star_idle_6',
    name: 'Galactic Supercluster Forge',
    description: '+1,000,000 Stars per second.',
    flavorText: 'Why forge a star when you can forge the home of a billion stars?',
    costResource: Resource.STAR,
    baseCost: 1000000000,
    costMultiplier: 2.0,
    effects: [{type: 'idle', resource: Resource.STAR, value: 1000000}],
    requiredEpoch: 6,
    position: { x: 80, y: 5 },
    parents: ['star_idle_5'],
  },
    'star_idle_7': {
    id: 'star_idle_7',
    name: 'Cosmic Crucible',
    description: '+100,000,000 Stars per second.',
    flavorText: 'Melt down neutron stars to forge new constellations.',
    costResource: Resource.STAR,
    baseCost: 1e12,
    costMultiplier: 2.2,
    effects: [{type: 'idle', resource: Resource.STAR, value: 100000000}],
    requiredEpoch: 6,
    position: { x: 50, y: 5 },
    parents: ['star_idle_3'],
  },

  // DARK MATTER BRANCH (Right side, starting Epoch 5)
  'dark_matter_unlock': {
    id: 'dark_matter_unlock',
    name: 'Non-Baryonic Matter',
    description: 'Discover Dark Matter. It will slowly accumulate.',
    flavorText: 'It\'s not what we see, it\'s what we don\'t see that matters.',
    costResource: Resource.STAR,
    baseCost: 500,
    costMultiplier: 1,
    maxLevel: 1,
    effects: [],
    requiredEpoch: 5,
    position: { x: 75, y: 30 },
    parents: ['atom_click_1'], // Branches from Atom logic
  },
  'dark_matter_generation': {
      id: 'dark_matter_generation',
      name: 'WIMP Detection',
      description: 'Generate Dark Matter based on your total Stars.',
      flavorText: 'Weakly Interacting Massive Particles. A shy bunch.',
      costResource: Resource.STAR,
      baseCost: 1000,
      costMultiplier: 1.5,
      effects: [], // Logic handled in Tick
      requiredEpoch: 5,
      position: { x: 85, y: 35 },
      parents: ['dark_matter_unlock'],
  },
  'dark_energy_expansion': {
      id: 'dark_energy_expansion',
      name: 'Dark Energy Expansion',
      description: 'Automates clicking! Each level triggers 1 click per second.',
      flavorText: 'The universe is pulling itself apart. Might as well use the momentum.',
      costResource: Resource.DARK_MATTER,
      baseCost: 10,
      costMultiplier: 1.3,
      effects: [], // Logic handled in Tick
      requiredEpoch: 5,
      position: { x: 90, y: 45 },
      parents: ['dark_matter_generation'],
  },
  'dark_gravity_assist': {
      id: 'dark_gravity_assist',
      name: 'Gravitational Lensing',
      description: 'Dark Matter passively boosts Star production.',
      flavorText: 'Bending light and destiny with invisible hands.',
      costResource: Resource.DARK_MATTER,
      baseCost: 50,
      costMultiplier: 1.4,
      effects: [], // Logic handled in App.tsx
      requiredEpoch: 5,
      position: { x: 95, y: 30 },
      parents: ['dark_matter_generation'],
  }
};

export const COSMIC_LAWS: CosmicLaw[] = [
  {
    epochIndex: 1, // Planck Epoch
    title: "Heisenberg's Uncertainty Principle",
    formula: "Δx * Δp ≥ ħ/2",
    explanation: "A fundamental limit to precision. You cannot simultaneously know the exact position and momentum of a particle. At this scale, the universe is a dance of probabilities.",
  },
  {
    epochIndex: 2, // Quark-Gluon Plasma
    title: "Mass-Energy Equivalence",
    formula: "E = mc²",
    explanation: "Energy and mass are two sides of the same coin. In this hot, dense soup, pure energy (E) is constantly converting into mass (m), creating a sea of fundamental particles.",
  },
  {
    epochIndex: 3, // Hadron & Lepton
    title: "The Strong Nuclear Force",
    explanation: "One of the four fundamental forces, it's what binds quarks together to form protons and neutrons. It's incredibly powerful but only acts over extremely short distances.",
  },
  {
    epochIndex: 4, // Nucleosynthesis
    title: "Stellar Nucleosynthesis",
    explanation: "The process by which elements are created within stars by fusion. For now, the universe has made Hydrogen and Helium. Heavier elements will require the heart of a star.",
  },
  {
    epochIndex: 5, // The First Stars
    title: "Kepler's Third Law of Planetary Motion",
    formula: "P² ∝ a³",
    explanation: "The square of a planet's orbital period (P) is proportional to the cube of its semi-major axis (a). This elegant law describes the relationship between the distance of a planet from its star and the time it takes to orbit.",
  },
  {
    epochIndex: 6, // Galaxy Formation
    title: "Newton's Law of Universal Gravitation",
    formula: "F = G * (m₁m₂/r²)",
    explanation: "The force of gravity (F) between two objects is proportional to the product of their masses and inversely proportional to the square of the distance between them. This is the architect of galaxies.",
  }
];

export const COMBO_DECAY_MS = 2000;

export const COMBO_TIERS = [
  { count: 10, multiplier: 2 },
  { count: 25, multiplier: 3 },
  { count: 50, multiplier: 5 },
  { count: 100, multiplier: 10 },
];

export const CRITICAL_CHANCE = 0.02; // 2% chance
export const CRITICAL_MULTIPLIER = 25; // 25x bonus

export const RANDOM_EVENT_CHANCE = 0.08; // Chance per check
export const RANDOM_EVENT_INTERVAL = 5000; // Check every 5 seconds

export const RANDOM_EVENTS: RandomEvent[] = [
  {
    id: 'black_hole',
    name: 'Black Hole Anomaly',
    description: 'A gravitational anomaly warps spacetime! All production is halved.',
    duration: 10000,
    effects: { idleMultiplier: 0.5, clickMultiplier: 0.5 },
    weight: 10,
    visualEffect: 'black-hole',
    requiredEpoch: 5,
  },
  {
    id: 'click_frenzy',
    name: 'Click Frenzy',
    description: 'A burst of cosmic energy supercharges your clicks! Click gains are quintupled.',
    duration: 15000,
    effects: { clickMultiplier: 5 },
    weight: 15,
    visualEffect: 'click-frenzy',
    requiredEpoch: 2,
  },
  {
    id: 'supernova',
    name: 'Supernova Burst',
    description: 'A nearby star has exploded! Bathed in its energy, your idle production is tripled.',
    duration: 20000,
    effects: { idleMultiplier: 3 },
    weight: 10,
    visualEffect: 'supernova',
    requiredEpoch: 5,
  },
  {
    id: 'cmb_radiation',
    name: 'Cosmic Microwave Background Radiation',
    description: 'Echoes of the Big Bang reveal a cache of primordial energy and quarks!',
    duration: 5000, // Duration for the visual effect
    effects: { instantGain: { [Resource.ENERGY]: 500, [Resource.QUARK]: 50 } },
    weight: 5,
    visualEffect: 'cmb-radiation',
    requiredEpoch: 2,
  },
  {
    id: 'strong_force_resonance',
    name: 'Strong Force Resonance',
    description: 'A harmonic in the strong nuclear force briefly makes proton formation more efficient!',
    duration: 5000,
    effects: { instantGain: { [Resource.PROTON]: 250 } },
    weight: 8,
    visualEffect: 'strong-force-resonance',
    requiredEpoch: 3,
  },
  {
    id: 'recombination_cascade',
    name: 'Recombination Cascade',
    description: 'A wave of cooling passes, allowing electrons and protons to combine into atoms with ease!',
    duration: 6000,
    effects: { instantGain: { [Resource.ATOM]: 500 } },
    weight: 8,
    visualEffect: 'recombination-cascade',
    requiredEpoch: 4,
  }
];

export const ACHIEVEMENTS: Record<string, Achievement> = {
    // Clicks
    'clicks_1': { id: 'clicks_1', name: 'Fiat Lux', description: 'Perform your first click.', condition: { type: 'clicks', target: 1 }},
    'clicks_100': { id: 'clicks_100', name: 'Persistent Tapper', description: 'Click 100 times.', condition: { type: 'clicks', target: 100 }},
    'clicks_1000': { id: 'clicks_1000', name: 'Cosmic Drummer', description: 'Click 1,000 times.', condition: { type: 'clicks', target: 1000 }},

    // Resources
    'energy_1k': { id: 'energy_1k', name: 'Pocket Full of Sunshine', description: 'Accumulate 1,000 Energy.', condition: { type: 'resource', resource: Resource.ENERGY, target: 1000 }},
    'energy_1m': { id: 'energy_1m', name: 'Dyson Sphere Candidate', description: 'Accumulate 1,000,000 Energy.', condition: { type: 'resource', resource: Resource.ENERGY, target: 1_000_000 }},
    'quarks_1k': { id: 'quarks_1k', name: 'Quark Connoisseur', description: 'Accumulate 1,000 Quarks.', condition: { type: 'resource', resource: Resource.QUARK, target: 1000 }},
    'protons_1k': { id: 'protons_1k', name: 'Positively Charged', description: 'Accumulate 1,000 Protons.', condition: { type: 'resource', resource: Resource.PROTON, target: 1000 }},
    'atoms_1k': { id: 'atoms_1k', name: 'Atomic Architect', description: 'Accumulate 1,000 Hydrogen Atoms.', condition: { type: 'resource', resource: Resource.ATOM, target: 1000 }},
    'stars_1': { id: 'stars_1', name: 'A Star is Born', description: 'Create your first Star.', condition: { type: 'resource', resource: Resource.STAR, target: 1 }},
    'stars_1k': { id: 'stars_1k', name: 'Constellation Chief', description: 'Create 1,000 Stars.', condition: { type: 'resource', resource: Resource.STAR, target: 1000 }},
    'stars_1m': { id: 'stars_1m', name: 'Galaxy Lord', description: 'Create 1,000,000 Stars.', condition: { type: 'resource', resource: Resource.STAR, target: 1_000_000 }},

    // Upgrades
    'upgrades_1': { id: 'upgrades_1', name: 'First Steps', description: 'Buy your first upgrade.', condition: { type: 'upgrade_level', target: 1 }},
    'upgrades_10': { id: 'upgrades_10', name: 'Tinkerer', description: 'Reach 10 total upgrade levels.', condition: { type: 'upgrade_level', target: 10 }},
    'upgrades_50': { id: 'upgrades_50', name: 'Cosmic Engineer', description: 'Reach 50 total upgrade levels.', condition: { type: 'upgrade_level', target: 50 }},
    'upgrades_100': { id: 'upgrades_100', name: 'Master of the Universe', description: 'Reach 100 total upgrade levels.', condition: { type: 'upgrade_level', target: 100 }},

    // Secret
    'secret_star': {
        id: 'secret_star',
        name: 'Cosmic Detective',
        description: 'You found a hidden anomaly in the fabric of spacetime!',
        condition: { type: 'secret', target: 'found_secret_star' },
        isSecret: true,
    },
};

export const PRESTIGE_UPGRADES: Record<string, PrestigeUpgrade> = {
  'primordial_power': {
    id: 'primordial_power',
    name: 'Primordial Power',
    description: (level) => `All Energy gains are increased by ${level * 2}%.`,
    baseCost: 1,
    costMultiplier: 1.25,
  },
  'idle_architects': {
    id: 'idle_architects',
    name: 'Idle Architects',
    description: (level) => `All idle resource production is increased by ${level * 2}%.`,
    baseCost: 1,
    costMultiplier: 1.25,
  },
  'critical_certainty': {
    id: 'critical_certainty',
    name: 'Critical Certainty',
    description: (level) => `Increases critical hit chance by +${(level * 0.1).toFixed(1)}%.`,
    baseCost: 5,
    costMultiplier: 1.5,
    maxLevel: 50, // Max of +5%
  },
  'cosmic_memory': {
    id: 'cosmic_memory',
    name: 'Cosmic Memory',
    description: () => `Start each new run with 5 free levels of "Quantum Fluctuation".`,
    baseCost: 10,
    costMultiplier: 1,
    maxLevel: 1,
  },
};